# Generated by Django 5.2 on 2025-04-18 22:20

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('condition_category', models.BooleanField(default=True, verbose_name='Category active/deactivated')),
                ('create_date_category', models.DateTimeField(auto_now_add=True, verbose_name='Create Date of Category')),
                ('update_date_category', models.DateTimeField(auto_now=True, verbose_name='Update Date of Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(max_length=150, verbose_name='Name of Author')),
                ('lastname_author', models.CharField(max_length=150, verbose_name='Lastname of Author')),
                ('facebook_author', models.URLField(blank=True, null=True, verbose_name='Facebook of Author')),
                ('twitter_author', models.URLField(blank=True, null=True, verbose_name='Twitter of Author')),
                ('instagram_author', models.URLField(blank=True, null=True, verbose_name='Instagram of Author')),
                ('web_author', models.URLField(blank=True, null=True, verbose_name='Web of Author')),
                ('email_author', models.EmailField(max_length=254, unique=True, verbose_name='Email of Author')),
                ('condition_author', models.BooleanField(default=True, verbose_name='Author active/deactivated')),
                ('create_date_author', models.DateTimeField(auto_now_add=True, verbose_name='Create Date of Author')),
                ('update_date_author', models.DateTimeField(auto_now=True, verbose_name='Update Date of Author')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'unique_together': {('name_author', 'lastname_author')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_post', models.CharField(max_length=100, unique=True, verbose_name='Title of Post')),
                ('slug_post', models.CharField(max_length=150, unique=True, verbose_name='Slug of Post')),
                ('description_post', models.CharField(max_length=200, verbose_name='Description of Post')),
                ('contents_post', ckeditor.fields.RichTextField(verbose_name='Contents of Post')),
                ('image_post', models.URLField(max_length=300, verbose_name='URL of Image')),
                ('condition_post', models.BooleanField(default=True, verbose_name='Publicationed/Not Publicationed')),
                ('create_date_post', models.DateTimeField(auto_now_add=True, verbose_name='Create Date of Post')),
                ('update_date_post', models.DateTimeField(auto_now=True, verbose_name='Update Date of Post')),
                ('author_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('category_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
