# Generated by Django 5.2 on 2025-04-11 15:35

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAuthor', models.CharField(max_length=150, verbose_name='Name of Author')),
                ('lastNameAuthor', models.CharField(max_length=150, verbose_name='Lastname of Author')),
                ('facebookAuthor', models.URLField(blank=True, null=True, verbose_name='Facebook of Author')),
                ('twitterAuthor', models.URLField(blank=True, null=True, verbose_name='Twitter of Author')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram of Author')),
                ('webAuthor', models.URLField(blank=True, null=True, verbose_name='Web of Author')),
                ('emailAuthor', models.EmailField(max_length=254, verbose_name='Email of Author')),
                ('conditionAuthor', models.BooleanField(default=True, verbose_name='Author active/deactivated')),
                ('createDateAuthor', models.DateTimeField(auto_now_add=True, verbose_name='Createdate of Author')),
                ('updateDateAuthor', models.DateTimeField(auto_now=True, verbose_name='Update Date of Author')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategory', models.CharField(max_length=100, verbose_name='Category Name')),
                ('conditionCategory', models.BooleanField(default=True, verbose_name='Category activa/deactivated')),
                ('createDateCategory', models.DateTimeField(auto_now_add=True, verbose_name='Createdate of Category')),
                ('updateDateCategory', models.DateTimeField(auto_now=True, verbose_name='Update Date of Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlePost', models.CharField(max_length=100, verbose_name='Title of Post')),
                ('slugPost', models.CharField(max_length=150, verbose_name='Slug of Post')),
                ('descriptionPost', models.CharField(max_length=200, verbose_name='Description of Post')),
                ('contentsPost', ckeditor.fields.RichTextField(verbose_name='Contents of Post')),
                ('imagePost', models.URLField(max_length=300, verbose_name='URL of Image')),
                ('conditionPost', models.BooleanField(default=True, verbose_name='Publicationed/Not Publicationed')),
                ('createDatePost', models.DateTimeField(auto_now_add=True, verbose_name='Createdate of Post')),
                ('updateDatePost', models.DateTimeField(auto_now=True, verbose_name='Update Date of Post')),
                ('authorPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('categoryPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
